### ISSUE TITLE
avahi-daemon timeout in azurelinux 3.0

### ISSUE THREAD

**Issue by LeisureLinux** [microsoft/azurelinux#10013]
× avahi-daemon.service - Avahi mDNS/DNS-SD Stack
     Loaded: loaded (/usr/lib/systemd/system/avahi-daemon.service; disabled; preset: enabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: timeout) since Sat 2024-08-03 09:41:08 CST; 1min 1s ago
TriggeredBy: ● avahi-daemon.socket
    Process: 768 ExecStart=/usr/sbin/avahi-daemon -s (code=killed, signal=TERM)
   Main PID: 768 (code=killed, signal=TERM)
        CPU: 45.122s

Aug 03 09:40:23 azurelinux-01 systemd[1]: Starting avahi-daemon.service - Avahi mDNS/DNS-SD Stack...
Aug 03 09:41:08 azurelinux-01 systemd[1]: avahi-daemon.service: start operation timed out. Terminating.
Aug 03 09:41:08 azurelinux-01 systemd[1]: avahi-daemon.service: Failed with result 'timeout'.
Aug 03 09:41:08 azurelinux-01 systemd[1]: Failed to start avahi-daemon.service - Avahi mDNS/DNS-SD Stack.
Aug 03 09:41:08 azurelinux-01 systemd[1]: avahi-daemon.service: Consumed 45.122s CPU time.

# uname -a
Linux azurelinux-01 6.6.35.1-5.azl3 #1 SMP PREEMPT_DYNAMIC Sat Jul 20 12:26:57 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

# grep -v ^# /etc/avahi/avahi-daemon.conf |grep .
[server]
use-ipv4=yes
use-ipv6=no
enable-dbus=no
ratelimit-interval-usec=1000000
ratelimit-burst=1000
[wide-area]
enable-wide-area=no
[publish]
publish-hinfo=no
publish-workstation=no
[reflector]
[rlimits]

**Comment by christopherco** [comment]
Thanks for reporting this issue. Please try out the updated `avahi-0.8-2.azl3` package, which should fix the hang in avahi-daemon
