### ISSUE TITLE
`python-poetry-core` doesn't declare some of its runtime dependencies, resulting in errors at runtime

### ISSUE THREAD

**Issue by surfacepatterns** [microsoft/azurelinux#10044]
**Describe the bug**
[The `python-poetry-core` spec](https://github.com/microsoft/azurelinux/blob/3.0/SPECS/python-poetry-core/python-poetry-core.spec) doesn't declare some of its runtime dependencies, which results in errors at runtime.

**To Reproduce**
1. Install the package.
2. Import modules that depend on packages that aren't available, e.g.:
    ```
    danderson [ ~ ]$ python3
    Python 3.12.3 (main, Jul 20 2024, 10:59:36) [GCC 13.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import poetry.core.json
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python3.12/site-packages/poetry/core/json/__init__.py", line 10, in <module>
        import fastjsonschema
    ModuleNotFoundError: No module named 'fastjsonschema'
    >>>
    ```

**Expected behavior**
Submodules are imported successfully.

I'll create a PR that solves this bug when I get a chance.

**Comment by mfrw** [comment]
Closed by:
- https://github.com/microsoft/azurelinux/pull/10046
