### ISSUE TITLE
Update built-in pyca/cryptography wheels (has a vulnerable OpenSSL included)  

### ISSUE THREAD

**Issue by grawcho** [microsoft/azurelinux#10637]
our acr is getting alert of CWE-1395 (https://github.com/advisories/GHSA-h4gh-qq45-vh27)
even though we don't have python3 / python3-pip or cryptography installed in the image (based on latest mariner-core:2.0)
and when trying to install from latest registry we get the patched version 43.0.1
please update the internal installed libs to repair this weakness.

OpenSsl is also in latest version.

**Comment by jslobodzian** [comment]
@grawcho this seems like it might be related to the installation of azure cli.  Can you confirm?

**Comment by grawcho** [comment]
Issue was caused by pre-installed azure-cli (python3.9/site-packages/cryptography), azure-cli latest version in dnf registry is now up to date (with cryptography 43.0.1), issue is gone.
Thanks.
