### ISSUE TITLE
Will Azure Linux replace CBL-Mariner form 3.0?

### ISSUE THREAD

**Issue by arisewanggithub** [microsoft/azurelinux#10703]
Will AzureLinux replace CBL-Mariner form 3.0? Or will CBL-Mariner will also be upgraded to 3.0 later to support node 20? AzureLinux has been upgraded to 3.0 for a while but CBL-Mariner is still on the old version.

**Comment by mfrw** [comment]
AzureLinux (aka CBL-Mariner) is the successor for CBL-Mariner.
We have renamed CBL-Mariner to AzureLinux. We will only keep on supporting AzureLinux 2.0 for security related fixes till its deprecation timeline.
