### ISSUE TITLE
AzureLinux 3.0 ISO link wrongly fetching 2.0 ISO Image in Github Server path

### ISSUE THREAD

**Issue by psw2kor** [microsoft/azurelinux#10724]
### Describe the bug
Installed the latest AzureLinux OS available in [Azure Linux 3.0 x86_64 ISO](https://aka.ms/azurelinux-3.0-x86_64.iso).
https://github.com/microsoft/azurelinux/blob/3.0/toolkit/docs/security/iso-image-verification.md
This seems to be **wrongly uploaded** and results in installation of 2.0 OS which comes with Linux 5.15.167.1-1.cm2 kernel by default.

## To Reproduce
1. Install AzureLinux 3.0 OS using the above mentioned ISO Image.
2. After OS installation, check the booting Image and confirm installed OS.

## Expected behavior
OS shows 2.0 Image installed instead of 3.0

## Observed behavior
System shows booting 2.0 OS with Linux 5.15.167.1-1.cm2 kernel.
```
$ cat /etc/os-release 
NAME="Common Base Linux Mariner"
VERSION="2.0.20241006"
ID=mariner
VERSION_ID="2.0"
PRETTY_NAME="CBL-Mariner/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://aka.ms/cbl-mariner"
BUG_REPORT_URL="https://aka.ms/cbl-mariner"
SUPPORT_URL="https://aka.ms/cbl-mariner"
..
..
$ cat /etc/lsb-release 
DISTRIB_ID="Mariner"
DISTRIB_RELEASE="2.0.20241006"
DISTRIB_CODENAME=Mariner
DISTRIB_DESCRIPTION="CBL-Mariner 2.0.20241006"
```

Please fix this issue at the earliest.

**Comment by anphel31** [comment]
Thank you for the report. We've just fixed the 3.0 ISO link. At the moment it should be providing the 3.0.20240824 ISO.

**Comment by psw2kor** [comment]
Newer uploaded ISO works fine and boots Azure Linux 3.0.
Thank you.

**Comment by psw2kor** [comment]
Hi @anphel31 

I see the latest uploaded Azure Linux 3.0 ISO image is quite old.

```
$ cat /etc/lsb-release 
DISTRIB_ID="azurelinux"
DISTRIB_RELEASE="3.0.20240824"
DISTRIB_CODENAME=AzureLinux
DISTRIB_DESCRIPTION="Azure Linux 3.0"
```

Also, it's still booting with **6.6.47** where as **6.6.51** kernel is already available.
https://github.com/microsoft/azurelinux/blob/3.0/SPECS/kernel/kernel.spec#L32

Do you know if this Image is just a workaround fix until proper Image is available ?

**Comment by anphel31** [comment]
Hi @psw2kor , we have recently updated the ISO, it should now be version `3.0.20241005` with kernel `6.6.51.1`

**Comment by psw2kor** [comment]
Thank you. Got the latest OS working fine. Thank you.
