### ISSUE TITLE
Add PowerShell to Azure Linux 3.0

### ISSUE THREAD

**Issue by dagood** [microsoft/azurelinux#10823]
**Is your feature request related to a problem? Please describe.**
I'm planning to write some logic in PowerShell to make it cross-platform and usable in anyone's Azure Linux 3.0 instance. I just learned that PowerShell isn't in Azure Linux 3.0 as of https://github.com/microsoft/azurelinux/pull/2799 and I don't see any issue already tracking reintroducing it.

> Removing powershell until powershell can be built using dotnet as a dependency rather than vendoring dotnet.

**Describe the solution you'd like**
An easily available PowerShell rpm package.

**Describe alternatives you've considered**
Directing Azure Linux 3.0 users of my script to install PowerShell using the prebuilt instructions provided at https://learn.microsoft.com/en-us/powershell/scripting/install/install-other-linux?view=powershell-7.4#installation-using-a-binary-archive-file.

**Additional context**
I saw some news in a Teams channel, but it isn't up to date:

https://teams.microsoft.com/l/message/19:44dcbdd98e934964a65cd55f84e0c8a4@thread.tacv2/1724262793706?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=5ef827e3-78d9-4463-b0fe-23c2727b4342&parentMessageId=1724262354024&teamName=Azure%20Linux%20(Mariner)%20Community&channelName=Packages&createdTime=1724262793706

**Comment by jperrin** [comment]
powershell is now available in azure linux 3.0.
