### ISSUE TITLE
Where is the source code of cloud-hypervisor-cvm ?

### ISSUE THREAD

**Issue by ohault** [microsoft/azurelinux#10965]
This is quite fondamental as it is about the trust one should be able to check of the infrastructure to run confidential computing workload?

**Comment by elsaco** [comment]
The latest release is at https://packages.microsoft.com/azurelinux/3.0/prod/base/srpms/Packages/c/cloud-hypervisor-cvm-38.0.72.2-2.azl3.src.rpm

**Comment by jperrin** [comment]
Question appears to be answered by @elsaco. Closing as there hasn't been much follow-up. Please re-open if there are additional concerns.
