### ISSUE TITLE
No rule to make target 'image'

### ISSUE THREAD

**Issue by billatarm** [microsoft/azurelinux#11280]
**Describe the bug**

Following the build steps at https://github.com/microsoft/azurelinux/blob/3.0/toolkit/docs/quick_start/quickstart.md:
```bash
sudo make image -j8 REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/core-efi.json
make: *** No rule to make target 'image'.  Stop.

I am on 3.0-stable, with HEAD pointed to:
```
commit 30d1349857d98c0c8710bd591d3a1676f502db20 (HEAD, tag: 3.0.20241101-3.0, tag: 3.0-stable)
Merge: ec7cffeff 75d1fc327
Author: jslobodzian <joslobo@microsoft.com>
Date:   Fri Nov 1 17:16:08 2024 -0400

    Merge branch '3.0-dev' into 3.0
```

It seems to be the most recent merge borked something. But with that said, I have never gotten a successful build on an AArch64 build host

```

**To Reproduce**
1. Follow the instructions here for VHD or VHDX builds: https://github.com/microsoft/azurelinux/blob/3.0/toolkit/docs/quick_start/quickstart.md
2. run `sudo make image -j8 REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/core-efi.json`
3. See error: `make: *** No rule to make target 'image'.  Stop.`

**Expected behavior**
Builds and works

**Comment by elsaco** [comment]
@billatarm you need to run the `make` command from within `toolkit` directory. If you try to invoke `make` from the top directory you'll get `No rule to make target 'image'` error:

```
elsaco@juno:~/azurelinux$ sudo make image -j4 REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/core-efi.json
make: *** No rule to make target 'image'.  Stop.
```

and from `toolkit`:

```
elsaco@juno:~/azurelinux/toolkit$ sudo make image -j4 REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/core-efi.json
cd /home/elsaco/azurelinux/toolkit/tools/ && \
        go test -ldflags="-X github.com/microsoft/azurelinux/toolkit/tools/internal/exe.ToolkitVersion=3.0.20241202.1732 -X github.com/microsoft/azurelinux/toolkit/tools/pkg/imagecustomizerlib.ToolVersion=0.6.0-dev.20241202.1732+ba13b4671 -X github.com/microsoft/azurelinux/toolkit/tools/internal/exe.DistroNameAbbreviation=azl -X github.com/microsoft/azurelinux/toolkit/tools/internal/exe.DistroMajorVersion=3" -test.short -covermode=atomic -coverprofile=/home/elsaco/azurelinux/build/tools/internal.test_coverage ./...
---cut---
```

Test done using `3.0-stable`:

```
commit ba13b467104263b5740cdca3054ea5121d8160ab (HEAD, tag: 3.0.20240910-3.0, tag: 3.0.20240824-3.0, tag: 3.0-stable)
Author: Daniel McIlvaney <damcilva@microsoft.com>
Date:   Tue Aug 27 13:59:31 2024 -0700

    fix: use static search path for toolchain GPG keys during validation (#10269)

commit 9f8d0fad669392e8c53e7334da1f481f5306e673
Merge: 027873ec5 bde321f1e
Author: jslobodzian <joslobo@microsoft.com>
Date:   Fri Aug 23 21:42:25 2024 -0400

    Merge branch '3.0-dev' into 3.0
```

**Comment by billatarm** [comment]
And it's clearly in the documentation. I was doing this, and then discarded that step.... Thank you!
