### ISSUE TITLE
https://microsoft.github.io/azurelinux/ has broken css and links

### ISSUE THREAD

**Issue by cleonte** [microsoft/azurelinux#11454]
**Describe the bug**
Hi Team,

when navigating to https://microsoft.github.io/azurelinux/ i see the css is broken, maybe a link to older repo?

also there are other broken links to cbl-marinner, can you try to fix?

**Comment by jperrin** [comment]
Yep, this appears to be related to the repo being renamed from cbl-mariner to azurelinux. For now I'm unpublishing the site. Thanks for reporting it.

**Comment by cleonte** [comment]
Hi Team,

any plan to publish it again?


Cheers
