### ISSUE TITLE
busybox should install links in CBL-Mariner's debug distroless images

### ISSUE THREAD

**Issue by bureado** [microsoft/azurelinux#2954]
The `debug` flavor of CBL-Mariner's _distroless_ images ships `busybox` arguably to support interactive debugging.

However, links aren't installed in `PATH` so users can only use the image if they know how to call Busybox's functions (e.g., `run -it ... 'busybox' 'sh'` instead of the arguably more expected and natural `run -it ... '/bin/sh'`)

One way to address this is to run `busybox --install` when creating the image. This is what's done in [docker-library/busybox](https://github.com/docker-library/busybox/search?q=install&type=). Or perhaps declaring the appropriate `ENTRYPOINT`.

It's also possible this is by-design, but I couldn't find a reference to _busybox install_ in Issues so it might be good to document it.

**Comment by OmegaVVeapon** [comment]
This definitely threw me off.
I was about to open a bug for the `debug` flavour before I found this issue.

**Comment by eric-desrochers** [comment]
@mandeepsplaha for visibility.

**Comment by Malateshk007** [comment]
@bureado, 
Thank you for reaching out and sharing your insightful suggestion.  We have made the appropriate updates to our documentation.

https://mcr.microsoft.com/en-us/product/cbl-mariner/distroless/debug/about
docker run -it --rm mcr.microsoft.com/cbl-mariner/distroless/debug:2.0 busybox sh

And your request is being supported in our next major release.
