### ISSUE TITLE
Replace FTP sources with HTTP or HTTPS

### ISSUE THREAD

**Issue by JamieMagee** [microsoft/azurelinux#3161]
Migrated from #1738.

Arch Linux[^1] and NixOS[^2] are useful references to identify alternative source locations

Packages identified using `rg -l -g "*.spec" "ftp://" | xargs dirname | xargs basename -s | sort`

- [ ] arpwatch
  - #3164
- [ ] aspell
  - #3189
- [ ] aspell-en
  - #3291
- [x] autoconf213
  - #3292
- [ ] colorize
  - `https://github.com/raszi/colorize` ?
- [ ] dhcp
  - `https://downloads.isc.org/isc/${pkgbase}/${_realver}/${pkgbase}-${_realver}.tar.gz`
- [ ] dialog
  - `https://invisible-mirror.net/archives/$pkgname/$pkgname-${pkgver/_/-}.tgz`
- [ ] diffstat
- [ ] docbook-utils
- [ ] freeradius
- [ ] freetds
- [ ] guile
- [ ] help2man
- [ ] hunspell-az
- [ ] hunspell-fa
- [ ] libfontenc
- [ ] libgsf
- [ ] librx
- [ ] libsmi
- [ ] libthai
- [ ] man-pages-it
- [ ] mpage
- [ ] mtools
- [ ] mtr
- [ ] mutt
- [ ] nvmetcli
- [ ] perl-DateTime-TimeZone
- [ ] perl-Net-Telnet
- [ ] plotutils
- [ ] postfix
- [ ] ppp
- [ ] procmail
- [ ] psacct
- [ ] python-alsa
- [ ] sendmail
- [ ] t1lib
- [ ] telnet
- [ ] time
- [ ] uuid
- [ ] xdelta
- [ ] xorg-x11-drv-libinput
- [x] xterm

[^1]: https://github.com/archlinux/svntogit-packages
[^2]: https://github.com/NixOS/nixpkgs

**Comment by Malateshk007** [comment]
@JamieMagee, Thank you for your valuable feedback. We will take it into consideration as we move forward. For now, I will proceed with closing the bug report.
