### ISSUE TITLE
add xdp-tools package to extended

### ISSUE THREAD

**Issue by dankamongmen** [microsoft/azurelinux#4408]
hey there! i'm using `xdp-tools` atop Mariner, and have to build it from source. i was hoping to provide a PR with `xdp-tools`, targeting extended (unless you want it in core), probably just cargo culting over the fedora specfile and beating on it if there's breakage.

if this would not be welcome, please let me know! otherwise i'll send up a PR and crossref this issue.

thanks!

**Comment by oliviacrain** [comment]
Hi! Feel free to make a PR importing the Fedora spec. Our team can also add the package, but then you'll be going through a bit of bureaucracy to get it assigned to someone. Once you get it building, we can guide you through all of the bits of linting, license record-keeping, and miscellaneous quality checks that we have.

We spent a lot of time last year working to make Fedora specs plug-and-play with Mariner- if the experience is painful at all, file a bug and we'll try to smooth things out.

In general, if there's any chance you'd want to use the package in a production environment, put it in core. Core packages are generally prioritized for security fixes.

**Comment by dankamongmen** [comment]
awesome, I've gone ahead and put up a PR, and am getting it to build now.

what is meant by "put it in core"? i don't see anything along those lines in `cgmanifest.json`...

**Comment by rlmenge** [comment]
"Core" is considered the set of packages which have the highest level of support. These are found under [SPECS](https://github.com/microsoft/CBL-Mariner/tree/main/SPECS)
Alternatively, you can additional packages to [SPECS-EXTENDED](https://github.com/microsoft/CBL-Mariner/tree/main/SPECS-EXTENDED)

**Comment by Malateshk007** [comment]
@dankamongmen, If you would like to continue pursuing this matter, please feel free to open a new bug report. We welcome further contributions and discussions through a new pull request. However, for the time being, we see no necessity to keep this particular bug report open. Thank you for your understanding and we look forward to your continued engagement.

**Comment by dankamongmen** [comment]
i have less than no interest in pursuing this matter, thanks!
