### ISSUE TITLE
can't install systemd 250.3-15.cm2.x86_64 due to missing systemd-rpm-macros

### ISSUE THREAD

**Issue by dankamongmen** [microsoft/azurelinux#5152]
Attempting to install a new Mariner machine or upgrade an existing one such that systemd-250.3-15.cm2.x86_64 is installed fails thanks to a missing 250.3-15.cm2.x86_64 version of systemd-rpm-macros. The most recent version in the Mariner repos appears to be 250.3-14.cm2.x86_64. Other systemd leaves show the most recent version (250.3-15.cm2.x86_64), including systemd-devel:

https://msazure.visualstudio.com/One/_build/results?buildId=70707985&view=logs&j=d721e18c-728e-5964-faa0-569cc84bfc34&t=422332a9-6ce3-5840-7ce8-5f26fdbedbcf&l=68

this has been going on all weekend, so I doubt that it's a repo sync issue or anything like that.

i hate to be dramatic, but this has brought our build and deployments to a screeching halt. if it's not fixed by Monday we'll need to start building our own systemd, which i'd really rather avoid doing. or perhaps i'm overlooking something and sound like an idiot? if you can point to an error of mine, that would be great. =] thanks!

**Comment by Malateshk007** [comment]
We would like to inquire if you are still encountering the issue with the latest version ("systemd.x86_64 -250.3-20.cm2"). If the problem persists, please do not hesitate to open a new bug report. We are in the process of closing this issue, and we appreciate your cooperation and contribution to improving our project. Thank you.
