### ISSUE TITLE
Recommendation for 1P consumers on selecting image tags.

### ISSUE THREAD

**Issue by Himanshg** [microsoft/azurelinux#5315]
What is the general guidance for 1P consumers on selecting the image tag for CBL-Mariner image?
One should always use the latest image (e.g., 2.0 currently) or use a specific build and update it periodically or need basis (e.g., some vulnerability getting flagged)?

**Comment by oaljoundi** [comment]
Hey @Himanshg, we'd recommend always pulling the latest image (2.0 tag) for easier management. For faster responses on 1P questions in the future, please join our Azure Linux (Mariner) support teams channel.

**Comment by eric-desrochers** [comment]
Seems like @oaljoundi already provided an answer. I'll go ahead and close this bug for now. Please re-open another one if you have other questions.
