### ISSUE TITLE
crashdump memory is reserved even if kdump (kexec-tools package) is not installed/enabled

### ISSUE THREAD

**Issue by ddstreet** [microsoft/azurelinux#5460]
The crashkernel= boot parameter causes the kernel to reserve a specific amount of memory. Currently this parameter is included in the Mariner kernel spec file, so all Mariner deployments reserve memory for a kdump kernel, on all boots. For systems where kexec-tools is not installed, no kdump kernel is loaded into the reserved memory, resulting in a loss of usable memory.

**Comment by Camelron** [comment]
This is addressed for 3.0 in the following commit: https://github.com/microsoft/CBL-Mariner/pull/6281

It will apply to all 3.0 images once we deprecate and remove the legacy boot.cfg and go full grub2-mkconfig by default. I'll leave this issue open until this one resolves. 

For 2.0, we want to keep the crashkernel allocation in the cmdline as we cannot safely ship its removal without causing other customers who _do_ use kexec-tools.service to go red.

**Comment by Malateshk007** [comment]
@Camelron has already provided an update on this matter, and I will proceed with closing this issue. Thank you for your engagement and please feel free to reach out if further discussion is needed.
