### ISSUE TITLE
Dracut package is lagging behind other distros.

### ISSUE THREAD

**Issue by dmcilvaney** [microsoft/azurelinux#5494]
Our [dracut package](https://github.com/microsoft/CBL-Mariner/blob/2.0/SPECS/dracut/dracut.spec) is becoming quite out of date. We need to decide on a new version for our next stable release.

We need to validate v59 (or later, depending on timelines) with our other packages.

We should also revisit our use of the `mkinitrd` tool that we resurrected to support our initramfs package.

fyi @ddstreet

**Comment by dmcilvaney** [comment]
Resolved by:
https://github.com/microsoft/azurelinux/pull/7743
https://github.com/microsoft/azurelinux/pull/8126

**Comment by LaszloGombos** [comment]
Dracut is now maintained at https://github.com/dracut-ng/dracut-ng as the earlier dracut repo is no longer maintained. v102 has been released 3 weeks ago - https://github.com/dracut-ng/dracut-ng/releases/tag/102.

Arch, Debian, Fedora, Gentoo, Ubuntu and many others has switched over to this new repo location and I hope you will also consider switching over. Please let me know if we can help out with the switch. Thank you and looking forward to working together upstream :-)

CC @ddstreetmicrosoft

**Comment by dmcilvaney** [comment]
Thanks for reaching out!
I noticed that a while back and we have a work-item to move forward, ideally for our new release.

**Comment by Camelron** [comment]
We have moved to dracut-ng's v102 tag in https://github.com/microsoft/azurelinux/pull/9501
