### ISSUE TITLE
When will nodejs 20 be supported?

### ISSUE THREAD

**Issue by arisewanggithub** [microsoft/azurelinux#6863]
From https://mcr.microsoft.com/en-us/product/cbl-mariner/base/nodejs/about, I can see CBL only supports nodejs 16 and 18 for now. When will nodejs 20 be supported? This is the current active LTS version.

**Comment by htaubenfeld** [comment]
Hi @arisewanggithub, nodejs 20 will likely be supported in our Mariner 3.0 release, which is expected to be released next year.

**Comment by infbase** [comment]
Can we get an update on this, as node.js 18 has been out of active support for some time?

**Comment by eric-desrochers** [comment]
Node.JS 18 is in Maintenance mode and will be supported upstream until ~Apr 2025 -> https://nodejs.org/en/about/previous-releases

There is no plan to upgrade to  Node.JS 20 for Mariner 2.0 lifetime.
Our new major release 3.0 release will include Node.JS 20.
