### ISSUE TITLE
Bash login results in bash: en_US: command not found

### ISSUE THREAD

**Issue by dashesy** [microsoft/azurelinux#6960]
**Describe the bug**
If you call `bash -l` or similarly run `tmux` you get the error.
This is because `/etc/profile` sources `/etc/profile.d/i18n.sh` which in turn `source /etc/locale.conf`, inside which there is string `en_US`.
Instead LANG should be set in i18n.sh

**To Reproduce**
1. bash -l
2. see `bash: en_US: command not found`

**Expected behavior**
No error

**Screenshots**
![image](https://github.com/microsoft/CBL-Mariner/assets/873905/cb92aaec-1eae-4260-bb5f-72012c33b192)

**Comment by eric-desrochers** [comment]
I cannot reproduce the situation on a newly deployed Mariner 2.0

```
root [ / ]# bash -l
root@aeeaccb80949 [ / ]#
```
