### ISSUE TITLE
Cgroupsv2 support in AKS

### ISSUE THREAD

**Issue by oaljoundi** [microsoft/azurelinux#6997]
Ships cgroupsv2 by default on the Azure Linux node in AKS, aligning with the AKS 1.29 release.

**Comment by Bryce-Soghigian** [comment]
https://github.com/Azure/karpenter/pull/72 karpenter defaults to cgroupsv2 for azure linux :)

**Comment by suhuruli** [comment]
Azure Linux 1.29 has defaulted to _cgroupsv2_ and marking this issue complete!
