### ISSUE TITLE
AKS Nodes dont include cloudapp.net search domain in resolv.conf of pods

### ISSUE THREAD

**Issue by OQCDoe** [microsoft/azurelinux#7228]
**Describe the bug**
We switched recently to AzureLinux in one of our AKS clusters and now we are noticing that our OpenTelemetry DaemonSets are throwing errors, because they cant query the node kubelet API. They are unable to resolve the node name via DNS, it turns out that the somerandomstring.frax.internal.cloudapp.net search domain is missing from resolv.conf. This only happens on AzureLinux nodes, all of our Ubuntu nodes are fine.

**To Reproduce**
1. Create AzureLinux Node Pool
2. Deploy OpenTelemetry kubeletstats Scraper
3. Open pod logs
```
{"level":"error","ts":1704896652.3717847,"caller":"scraperhelper/scrapercontroller.go:200","msg":"Error scraping metrics","kind":"receiver","name":"kubeletstats","data_type":"metrics","error":"Get \"https://aks-default-123456789-vmss000000:10250/stats/summary\": dial tcp: lookup aks-default-123456789-vmss000000 on 10.10.10.10:53: no such host","scraper":"kubeletstats","stacktrace":"go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport\n\tgo.opentelemetry.io/collector/receiver@v0.88.0/scraperhelper/scrapercontroller.go:200\ngo.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1\n\tgo.opentelemetry.io/collector/receiver@v0.88.0/scraperhelper/scrapercontroller.go:176"}
```

AzureLinux resolv.conf in pod:
```
cat /etc/resolv.conf 
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.10.10.10
options ndots:5
```

Ubuntu resolv.conf of pod:
```
cat /etc/resolv.conf 
search default.svc.cluster.local svc.cluster.local cluster.local somerandomstring.frax.internal.cloudapp.net
nameserver 10.10.10.10
options ndots:5
```

**Expected behavior**
Pods are able to resolve the node ip via node name in cluster DNS

**Comment by ddstreetmicrosoft** [comment]
I believe k8s pulls the trailing search domains from the host (node) resolv.conf file, are you able to provide that file content?

**Comment by ddstreetmicrosoft** [comment]
this appears to be the result of Ubuntu defaulting systemd-networkd parameter UseDomains=true, while Mariner defaults to UseDomains=false (I believe upstream systemd also defaults to false).

**Comment by OQCDoe** [comment]
> I believe k8s pulls the trailing search domains from the host (node) resolv.conf file, are you able to provide that file content?

The resolv.conf of the node exclusively contains the domain that is missing from all pods:

```
search abcuniqueidxyz.frax.internal.cloudapp.net
nameserver 168.63.129.16
```


> this appears to be the result of Ubuntu defaulting systemd-networkd parameter UseDomains=true, while Mariner defaults to UseDomains=false (I believe upstream systemd also defaults to false).

Is there any way to configure this when deploying a node pool?

**Comment by henryli001** [comment]
Opened PR to resolve this issue for Azure Linux AKS: https://github.com/Azure/AgentBaker/pull/4366
