### ISSUE TITLE
Newer cmake package version (> 3.22)

### ISSUE THREAD

**Issue by alexefro** [microsoft/azurelinux#7260]
Newer releases of cmake contain useful features, such as built-in support for install-by-softlink
[CMAKE_INSTALL_MODE](https://cmake.org/cmake/help/v3.22/envvar/CMAKE_INSTALL_MODE.html
)

What are the plans for advancing cmake version past 3.22?

**Comment by anphel31** [comment]
Updates to our stable release (2.0) are driven by CVE fixes, so we would likely not upgrade cmake on 2.0 unless we need to, in order to fix a vulnerability issue.
For 3.0, we've already updated cmake to 3.28.2, see the linked PR above.
