### ISSUE TITLE
widespread use of invalid %{with_check} macro prevents using many standard tools with our spec files

### ISSUE THREAD

**Issue by ddstreetmicrosoft** [microsoft/azurelinux#7342]
**Describe the bug**

many of our spec files contain the invalid macro %{with_check}, which is not a valid macro and only defined when using our 'make' process. This results in the inability to use any of these invalid spec files with standard rpm tooling (e.g. rpmbuild, spectool, etc).

**To Reproduce**

```
# rpmbuild -bb wget.spec 
error: parse error in expression:  %{with_check}
error:                             ^
error: /usr/src/mariner/SPECS/wget.spec:12: bad %if condition:  %{with_check}

```

**Comment by ddstreetmicrosoft** [comment]
@dmcilvaney @PawelWMS for 3.0 (at least) we need to replace use of this invalid macro with something standard, which will require toolkit changes as well as fixing all the spec files.

fyi @christopherco @jslobodzian @Britel

**Comment by mfrw** [comment]
I sometimes get over it by `rpmbuild -D "with_check 1" .....` {1/0 depending if i want check or not}

**Comment by dmcilvaney** [comment]
Would it be sufficient to define a default in our macros package? Or is the request that we use a standard mechanism (%bcond*) and update the packages to use that? Obviously the macro path is quicker, but would mean that the tools in question either need to explicitly import the mariner macros files (we do this for PR gates on Ubuntu), or be run on Mariner.
