### ISSUE TITLE
Backport request for 2.0: golang: include go.env in GOROOT 

### ISSUE THREAD

**Issue by sozercan** [microsoft/azurelinux#8268]
**Describe the bug**
https://github.com/microsoft/azurelinux/pull/8021

Affects msft-golang in Azure Linux 2.0 too

```
$ go mod download
go: cloud.google.com/go/compute@v1.23.4: GOPROXY list is not the empty string, but contains no entries
```

cc @mfrw @dagood 

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or log outputs to help explain your problem.

**Comment by mfrw** [comment]
PR merged to `main` for inclusion in the next 2.0 release.
