### ISSUE TITLE
Cgroup v2 support

### ISSUE THREAD

**Issue by grzesuav** [microsoft/azurelinux#8377]
**Is your feature request related to a problem? Please describe.**
It seems Azure Linux supports only `crgoup  v1`
**Describe the solution you'd like**

Support `cgroup v2`

**Describe alternatives you've considered**

none

**Additional context**

**Comment by suhuruli** [comment]
Hi @grzesuav, as of AKS 1.29, Azure Linux defaults to cgroupsv2.

**Comment by eric-desrochers** [comment]
Seems like @suhuruli already cover this question. Please re-open the bug if you have other unanswered questions for this topic.
