### ISSUE TITLE
lspci returns no results

### ISSUE THREAD

**Issue by sirredbeard** [microsoft/azurelinux#8436]
**Describe the bug**

lspci returns no results.

**To Reproduce**
1. `tdnf install pciutils pciutils-libs hwdata -y`
2. `pciutils`

**Expected behavior**

There is no output, even after running `update-pciids`.

**Screenshots**

![image](https://github.com/microsoft/azurelinux/assets/33820650/2019dce7-d14c-4183-a14e-1c1d02e6845e)

**Comment by mfrw** [comment]
If accelerated networking is disabled, this is expected as none of the mlx/mana(network) or nvme(disks) pci devices are exposed.

**Comment by kanikanema** [comment]
@mfrw what VM sku is this? If the VM does not include any emulated/virtual PCI devices then this is expected as there is nothing listed.
