### ISSUE TITLE
dotnet: missing dependency for dotnet-hostfxr and hostfxr not published

### ISSUE THREAD

**Issue by Camelron** [microsoft/azurelinux#8595]
**Describe the bug**
The dotnet binary has a codepath with requires a binary provided by dotnet-hostfxr but the package manager doesn't know about this requirement. Furthermore, dnf whatprovides finds hostfxr subpackage but is unable to resolve it with dnf install. 

**To Reproduce**
cameronbaird@cam-mariner [ ~/repos/mariner-2 ]$ sudo dnf install dotnet-host -y
...
cameronbaird@cam-mariner [ ~/repos/mariner-2 ]$ dotnet tool install -g git-credential-manager
Error: [/usr/share/dotnet/host/fxr] does not exist
cameronbaird@cam-mariner [ ~/repos/mariner-2 ]$ sudo dnf whatprovides /usr/share/dotnet/host/fxr
Last metadata expiration check: 0:00:48 ago on Thu Mar 28 20:44:11 2024.
dotnet-hostfxr-6.0-6.0.5-1.x86_64 : Microsoft .NET Host FX Resolver - 6.0.5
Repo        : mariner-official-microsoft
Matched from:
Filename    : /usr/share/dotnet/host/fxr
**Expected behavior**

When I try to remedy the missing dep manually:
sudo dnf install dotnet-hostfxr -y
Last metadata expiration check: 0:03:36 ago on Thu Mar 28 20:44:11 2024.
No match for argument: dotnet-hostfxr
Error: Unable to find a match: dotnet-hostfxr

**Screenshots**
If applicable, add screenshots or log outputs to help explain your problem.

**Comment by Camelron** [comment]
Found this when following: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-security-configuration/configuration-guides/gcm?tabs=linux-install

**Comment by eric-desrochers** [comment]
Might be worth reporting a bug against https://github.com/dotnet/core/issues. They are the maintainer of the Mariner binary packages. Closing this bug for now.
