### ISSUE TITLE
tdnf: "Error(1261) : SSL peer certificate or SSH remote key was not OK" in WSL System Distro

### ISSUE THREAD

**Issue by sirredbeard** [microsoft/azurelinux#8751]
**Describe the bug**

tdnf and yum cannot be used to install packages in the WSL System Distro due to SSL issue:

```
root@XPS15 [ /mnt/c/Users/hayden ]# tdnf update
Loaded plugin: tdnfrepogpgcheck
Refreshing metadata for: 'CBL-Mariner Official Extras 2.0 x86_64'
retrying 1/10
retrying 2/10
retrying 3/10
retrying 4/10
retrying 5/10
retrying 6/10
retrying 7/10
retrying 8/10
retrying 9/10
retrying 10/10
Error(1261) : SSL peer certificate or SSH remote key was not OK
Error: Failed to synchronize cache for repo 'CBL-Mariner Official Extras 2.0 x86_64'
```
Same applies to:
```
'CBL-Mariner Official Extras 2.0 x86_64'
'CBL-Mariner Official Microsoft 2.0 x86_64'
```

I understand the system distro is ephemeral and changes are list when the system distro is stopped.

However, when developing tooling for WSL, I occasionally drop into the system distro because it is a universal standard environment to work from, regardless of what WSL distros a user has installed.

Some of these tools need to grab dependencies using tdnf. These tools are temporarily broken due to this SSL issue.

```
WSL version: 2.2.1.0
Kernel version: 5.15.150.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22635.3420
```

**To Reproduce**

1. Run `wsl.exe --system --user root`
2. Run `tdnf update`

**Expected behavior**

`tdnf` or `yum` update from the CBL-Mariner repository.

**Screenshots**

![image](https://github.com/microsoft/azurelinux/assets/33820650/b11127d5-8c98-4f15-9b8d-6898f7c5fc52)

**Comment by elsaco** [comment]
Bad certificates. Please see https://github.com/microsoft/azurelinux/issues/8593#issuecomment-2030810649

**Comment by sirredbeard** [comment]
Ah, fixed with `wsl.exe --update --pre-release`. Thank you. 
![image](https://github.com/microsoft/azurelinux/assets/33820650/e4cf32db-1f04-496d-9bbd-b3ca0320cbf8)
