### ISSUE TITLE
NodeJS 18 support beyond 18.18.2

### ISSUE THREAD

**Issue by JakovS** [microsoft/azurelinux#8947]
**Is your feature request related to a problem? Please describe.**
https://mcr.microsoft.com/v2/cbl-mariner/base/nodejs/tags/list
https://mcr.microsoft.com/en-us/product/cbl-mariner/base/nodejs/about

There are no images for Node JS beyond 18.18.2. While NodeJS 20 is only supported in next major of Mariner (#6863), I would expect 18.20.2 (current LTS) image to be supported.

**Describe the solution you'd like**
`nodejs:18.20-cm2.0` image to be made available, keep up to date with LTS versions for patches and security vulnerability fixes.

**Describe alternatives you've considered**
Manually overriding the version provided by the image

**Additional context**
![image](https://github.com/microsoft/azurelinux/assets/3286780/1a36f4e2-5365-4fb0-bff9-71332a901322)

**Comment by Meir017-msft** [comment]
this is required to mitigate https://github.com/advisories/GHSA-prhj-8562-p8gj

**Comment by Meir017-msft** [comment]
looks like this was resoved in #8982

**Comment by JakovS** [comment]
I can see it in tag list now, but still not in mcr portal. Will keep this open until that propagates.

**Comment by JakovS** [comment]
I can see it published to mcr now. Closing this.
