### ISSUE TITLE
How to enable users with unattended install for baremetal install, not VM?

### ISSUE THREAD

**Issue by cwyborny** [microsoft/azurelinux#9145]
Using the SystemConfigs user section for an unattended install iso on a baremetal system, no HyperV.  Custom image config attached for reference.  Users with plaintext passwords cannot login after image generation.  Not sure whether the user doesn't exist or the password isn't correct can't login and get access to logs.  

[core-legacy-unatt-sme-user.json](https://github.com/microsoft/azurelinux/files/15355809/core-legacy-unatt-sme-user.json)

**Comment by elsaco** [comment]
@cwyborny you need to specify that the password is not hashed. Here's an example used for testing:

```
            "Users": [
                 {
                 "Name": "root",
                 "Password": "intel321",
                 "PasswordHashed": false
             },
             {
                     "Name": "elsaco",
                     "Password": "intel123",
                     "PasswordHashed": false
             }
          ]
```

Upon deployment the installer will hash the passwords accordingly. Output of  `/etc/shadow`:

```
elsaco@azurelinux [ ~ ]$ sudo getent shadow
root:$6$gGzclH2cBtR5$Krz2AWKQNxQoA8y9FQusJQQPOl0.mhO79z.a.yv30he8hRCDg3TcomW58Wnt6.JNnMga2O7DoGgX9HAZXq2Fk/:19862:7:99999:7:::
bin:x:19862:7:99999:7:::
daemon:x:19862:7:99999:7:::
messagebus:x:19862:7:99999:7:::
systemd-bus-proxy:x:19862:7:99999:7:::
systemd-journal-gateway:x:19862:7:99999:7:::
systemd-journal-remote:x:19862:7:99999:7:::
systemd-journal-upload:x:19862:7:99999:7:::
systemd-network:x:19862:7:99999:7:::
systemd-resolve:x:19862:7:99999:7:::
systemd-timesync:x:19862:7:99999:7:::
systemd-coredump:x:19862:7:99999:7:::
systemd-oom:x:19862:7:99999:7:::
nobody:x:19862:7:99999:7:::
chrony:!:19862::::::
elsaco:$6$0DdR0PSBmV6J$EbUcA0TPSyck0BNYZP90l6On.bXIS2dMP8Q2dCLzO7SH83d4lP7QDz5/DFxnO32YVJ7RINbIS9qvMi/UW9Ha2.:19862:7:99999:7:::
mariner:!:19862:7:99999:7:::
sshd:!:19862::::::
```

You could also use `PasswordHased: false` in your image config and provide your own hashes:

```
elsaco@azurelinux [ ~ ]$ openssl passwd -6 -salt 0DdR0PSBmV6J intel123
$6$0DdR0PSBmV6J$EbUcA0TPSyck0BNYZP90l6On.bXIS2dMP8Q2dCLzO7SH83d4lP7QDz5/DFxnO32YVJ7RINbIS9qvMi/UW9Ha2.
```

You'll have to provide the `salt`. I just used the one created during install. Notice how the shadow hash for users `elasco` matches the example above.

**Comment by cwyborny** [comment]
Thanks for this.  We tried setting PasswordHashed: false and it still fails to login in the users with plaintext passwords.  Since we are doing unattended installs, we cannot get a user to login to the newly installed system and have had challenges in changing anything or seeing any logs for errors.  We can try doing a manual install with a preconfigured user and see if we can find any more info for this issue.

**Comment by cwyborny** [comment]
I also tried a hashed password and it failed as well.  We will try with a regular install vs. unattended and see if we can get more info on the failure.  We really need the unattended install, so if there is more documentation on that somewhere for Azure Linux, that would be helpful.

**Comment by elsaco** [comment]
Mount the ISO and inspect `config/unattended_config.json`. Your user(s) information should be in that file otherwise no users will be created during unattended deployment. The user section should look like this, just different user name/password:

```
  "Users": [
   {
    "Name": "root",
    "UID": "",
    "PasswordHashed": false,
    "Password": "intel321",
    "PasswordExpiresDays": 0,
    "SSHPubKeyPaths": null,
    "SSHPubKeys": null,
    "PrimaryGroup": "",
    "SecondaryGroups": null,
    "StartupCommand": ""
   },
   {
    "Name": "elsaco",
    "UID": "",
    "PasswordHashed": false,
    "Password": "intel123",
    "PasswordExpiresDays": 0,
    "SSHPubKeyPaths": null,
    "SSHPubKeys": null,
    "PrimaryGroup": "",
    "SecondaryGroups": null,
    "StartupCommand": ""
   }
  ],
```

**Comment by elsaco** [comment]
I tried your config and it's not creating users indeed:

`"Users": null` 

User information should be under `SystemConfigs` tag, Remove the `]` before defining users.

**Comment by cwyborny** [comment]
Thanks for this, totally missed that extra bracket, obviously.  Now when I build, I'm getting some additional errors, so I think I'm missing some things for a real unattended install.  I've grepped through the tools code for this message and found that the imager code adds this flag, but I can't seem to find out what I need to do in my build to enable it properly.  See attached screen shot of the error.
![image](https://github.com/microsoft/azurelinux/assets/50000710/de6403fc-abbc-4891-89d0-9e75b25d8a48)

**Comment by elsaco** [comment]
When building the ISO the `UNATTENDED_INSTALLER=y` must be added. This is the command I use to create unattended installs, and it works okay:

`sudo make iso REBUILD_TOOLS=y UNATTENDED_INSTALLER=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/your_config_here.json`

Please post the `make` command you're using.

**Comment by cwyborny** [comment]
I need to double check something.  I was trying to build some VHD images for testing user generation and was using make image, not make iso..  command was: make image QUICK_REBUILD=y CONFIG_FILE=./imageconfigs/core-legacy-unattended-hyperv.json UNATTENDED_INSTALLER=y 

However, using the make iso.. seems to be working.  Will double check the resultant user creation once its done.

**Comment by cwyborny** [comment]
Ok, iso created and configured users appear in config/unattended_config.json.  Thanks for the help!
