### ISSUE TITLE
glibc-debuginfo isn't available in package repository

### ISSUE THREAD

**Issue by pareshverma91** [microsoft/azurelinux#9228]
**Describe the bug**
Valgrind spec requires glibc-debuginfo package. https://github.com/microsoft/azurelinux/blob/59ce246f224f282b3e199d9a2dacaa8011b75a06/SPECS/valgrind/valgrind.spec#L12C1-L13C1. However, the package doesn't exist in the package repositories for Mariner.
```bash
# tdnf search glibc-debuginfo
Loaded plugin: tdnfrepogpgcheck
Error(1599) : No matches found
```

**To Reproduce**
1. Run `tdnf install valgrind`.
2. It fails with error
```bash
# tdnf install valgrind
Loaded plugin: tdnfrepogpgcheck
1. nothing provides glibc-debuginfo needed by valgrind-3.22.0-1.cm2.x86_64
Found 1 problem(s) while resolving
Error(1301) : Solv general runtime error
```

**Expected behavior**
Valgrind installation should succeed without any issues, since the package is supported by Azure Linux.

**Comment by zcobol** [comment]
@pareshverma91 the package is available, you just need to configure your package manager to pull from `https://packages.microsoft.com/cbl-mariner/2.0/prod/base/debuginfo/x86_64/` also.

After adding the `debuginfo` repo it works:

```
zcobol@azurelinux [ ~ ]$ sudo tdnf install valgrind
Loaded plugin: tdnfrepogpgcheck
Refreshing metadata for: 'cbl-mariner/2.0/prod/base/debuginfo/x86_64'
mariner-official-debug                  453503 100%
Installing:
glibc-debuginfo            x86_64              2.35-7.cm2                 mariner-official-debug  65.56M              15.69M
valgrind                   x86_64              3.22.0-1.cm2               mariner-official-base  57.82M              16.04M

Total installed size: 123.38M
Total download size:  31.74M
Is this ok [y/N]: 
```

**Comment by mfrw** [comment]
Doing a `tdnf install mariner-repos-debug` installs the debug-info yum repository.
