### ISSUE TITLE
SQL ODBC driver doesn't work on cbl-mariner python image

### ISSUE THREAD

**Issue by dylanw-oss** [microsoft/azurelinux#9234]
**Describe the bug**
Trying to use cb-mariner python image to query SQL table, failed.

**To Reproduce**
1. Setup an image and install SQL ODBC drivers:
```
FROM mcr.microsoft.com/cbl-mariner/base/python:3.9-cm2.0
...
RUN curl https://packages.microsoft.com/config/rhel/7/prod.repo > /etc/yum.repos.d/mssql-release.repo && \
    ACCEPT_EULA=Y yum install -y msodbcsql17 unixODBC unixODBC-devel && \
    yum clean all
 
# Set the environment variable for ODBC library path
ENV LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/usr/local/lib64:/usr/lib64
```
2. Create an instance and connect to its shell
`docker run -it <imageid> sh`
3. Connect to SQL table
 `isql -v -k "DRIVER={ODBC Driver 17 for SQL Server};SERVER=<serverName>.database.windows.net;DATABASE=<databaseName>;UID=<uid>;PWD=<pwd>"`
[IM004][unixODBC][Driver Manager]Driver's SQLAllocHandle on SQL_HANDLE_HENV failed
[ISQL]ERROR: Could not SQLDriverConnect

**Expected behavior**
Get "Connected! " Successfully.

**Screenshots**
I also tried to get traces, 
`strace -t -f -o trace_out.txt isql -v -k "<connection string>"`
saved logs as file: [sql_logs.txt](https://github.com/microsoft/azurelinux/files/15474064/sql_logs.txt)

And there is no such issue when using ubuntu as docker image:
```
FROM ubuntu:20.04
ARG UBUNTU_VERSION=20.04
...
# Install required packages and setup MS SQL Server repository
RUN apt-get update && apt-get install -y \
    curl \
    apt-transport-https \
    && curl https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc \
    && curl https://packages.microsoft.com/config/ubuntu/${UBUNTU_VERSION}/prod.list | tee /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql17 \
    && ACCEPT_EULA=Y apt-get install -y mssql-tools \
    && echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc \
    && apt-get install -y unixodbc-dev \
    && rm -rf /var/lib/apt/lists/*


# Source .bashrc to update PATH
RUN /bin/bash -c "source ~/.bashrc"
```

**Comment by zcobol** [comment]
@dylanw-oss not sure why you're installing drivers from `RHEL7` repo since CBL-Mariner has those packages available also. Using the `ODBC Driver 17 for SQL Server` it connects to the server as expected:

```
isql -v -k "DRIVER={ODBC Driver 17 for SQL Server};SERVER=192.168.1.115;DATABASE=Test101;UID=zcobol;PWD=password"
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+
SQL> quit
```

`/home/zcobol/.odbc.ini` driver info:

```
zcobol [ /home/zcobol ]# cat .odbc.ini
[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.10.so.6.1

```

**Comment by dylanw-oss** [comment]
@zcobol, thanks! Can you share your docker file? what's the base image you used and how did you install the driver?
The driver is not available when I use this as base image:
`FROM mcr.microsoft.com/cbl-mariner/base/python:3.9-cm2.0`

**Comment by dylanw-oss** [comment]
Resolved! Remove RHEL7 repo and it works! Thanks!

```FROM mcr.microsoft.com/cbl-mariner/base/python:3.9-cm2.0

RUN ACCEPT_EULA=Y yum install -y msodbcsql17 unixODBC unixODBC-devel && \
    yum clean all

```
