### ISSUE TITLE
Package `azcopy` is shipping `azcopy_linux_amd64` instead of `azcopy`

### ISSUE THREAD

**Issue by surajssd** [microsoft/azurelinux#9464]
**Describe the bug**

If I install `azcopy` in Mariner 2.0, I get `azcopy_linux_amd64` instead of `azcopy`.

**To Reproduce**

Start a mariner container image:

```bash
docker run -it mcr.microsoft.com/cbl-mariner/base/core:2.0 bash
```

Once inside the container:

```bash
tdnf install -y azcopy
```

Look for `azcopy`:

```bash
which azcopy
```

**Expected behavior**

**Screenshots**

Here is a sample run that I did:

```bash
$ docker run -it mcr.microsoft.com/cbl-mariner/base/core:2.0 bash

root [ / ]# tdnf install -y azcopy
Loaded plugin: tdnfrepogpgcheck
Refreshing metadata for: 'CBL-Mariner Official Extras 2.0 x86_64'
Refreshing metadata for: 'CBL-Mariner Official Base 2.0 x86_64'
Refreshing metadata for: 'CBL-Mariner Official Microsoft 2.0 x86_64'
mariner-official-microsoft               36133 100%
Installing:
azcopy                                x86_64                       10.25.0~preview.2-1                   mariner-official-microsoft    31.82M                        15.35M

Total installed size:  31.82M
Total download size:  15.35M
azcopy                                16090683 100%
importing key from file:///etc/pki/rpm-gpg/MICROSOFT-RPM-GPG-KEY
importing key from file:///etc/pki/rpm-gpg/MICROSOFT-METADATA-GPG-KEY
Testing transaction
Running transaction
Installing/Updating: azcopy-10.25.0~preview.2-1.x86_64

root [ / ]# which azcopy
bash: which: command not found

root [ / ]# azcopy_linux_amd64 -v
azcopy version 10.25.0~preview.2
```

**Comment by surajssd** [comment]
What's interesting is that azcopy version that is being installed and the one on the `packages.microsoft.com` do not match.

<img width="776" alt="image" src="https://github.com/microsoft/azurelinux/assets/5815795/74a9e75f-b0f8-41fd-b1cb-d832a784bbb9">
Source: https://packages.microsoft.com/cbl-mariner/2.0/prod/base/x86_64/Packages/a/

**Comment by zcobol** [comment]
The container is pulling from 3 repos:

```
repo id             repo name                                status
mariner-official-extras CBL-Mariner Official Extras 2.0 x86_64   enabled
mariner-official-microsoft CBL-Mariner Official Microsoft 2.0 x86_64 enabled
mariner-official-base CBL-Mariner Official Base 2.0 x86_64     enabled
```

and `CBL-Mariner Official Microsoft 2.0 x86_64` offers the `azcopy` package with the highest version. However, it is a bad package:

 https://packages.microsoft.com/cbl-mariner/2.0/prod/Microsoft/x86_64/Packages/a/azcopy-10.25.0~preview.2-1.x86_64.rpm

**Comment by jepio** [comment]
Looks like the package has been pulled.

**Comment by jperrin** [comment]
Closing this out, as the offending package has been removed.
