### ISSUE TITLE
vim syntax highlight is not working in CBL-Mariner 2.0

### ISSUE THREAD

**Issue by jslhcl** [microsoft/azurelinux#9536]
**Describe the bug**
VIM syntax highlight is not working in CBL-Mariner 2.0

**To Reproduce**
1. ssh to a CBL-Mariner VM through PowerShell
2. open a python file with vim, no syntax highlighted

I've already set 

filetype plugin on
syntax on

in my ~/.vimrc file

It looks the syntax files (such as python.vim) is not included in /usr/share/vim/vim90/syntax folder. But even if I add it from vim repro, the syntax highlight is still not working

**Comment by zcobol** [comment]
@jslhcl install `vim-extra` package also to get syntax coloring:

```
Name         : vim-extra
Version      : 9.0.2121
Release      : 2.cm2
Architecture : x86_64
Size         : 9.1 M
Source       : vim-9.0.2121-2.cm2.src.rpm
Repository   : mariner-official-base
Summary      : Extra files for Vim text editor
URL          : https://www.vim.org
License      : Vim
Description  : The vim extra package contains a extra files for powerful text editor.
```

**Comment by mfrw** [comment]
@jslhcl please feel to reopen if the problem persists even after installing `vim-extra`

**Comment by jslhcl** [comment]
yes, "sudo dnf install vim-extra" works. Thanks a lot!
