### ISSUE TITLE
drop 0002-disable-xattr.patch

### ISSUE THREAD

**Issue by LaszloGombos** [microsoft/azurelinux#9580]
Instead of the patch, this can be achieved with a configuration file (e.g. `50-no-xattr.conf`)

```
# disable xattr
DRACUT_NO_XATTR=1
```

CC @Camelron

**Comment by Camelron** [comment]
Thanks! Looking into dropping this one.

**Comment by Camelron** [comment]
Resolved, thanks for bringing this one up!
