### ISSUE TITLE
Azure linux 3.0 release

### ISSUE THREAD

**Issue by craftzneko** [microsoft/azurelinux#9726]
Waiting for pg dump to be updated on Azure Cloud Shell. Issues was answered by directing here to ask the following

https://github.com/Azure/CloudShell/issues/383

Good question, I would ask that in https://github.com/microsoft/azurelinux/issues for when Azure Linux 3.0 will be the default in [packages.microsoft.com](https://packages.microsoft.com/cbl-mariner/).

So based on above when will azure linux 3.0 be default

**Comment by mfrw** [comment]
GA Release link:
https://github.com/microsoft/azurelinux/releases/tag/3.0.20240727-3.0
