### ISSUE TITLE
Missing feature systemd/systemctl?

### ISSUE THREAD

**Issue by TheOnlyWei** [microsoft/azurelinux#9886]
**Is your feature request related to a problem? Please describe.**
I would like the core Azure Linux Mariner image to contain `systemctl` command as advertised by this document:
https://microsoft.github.io/azurelinux/docs/#managing-services-with-systemd

However, the latest version (`mcr.microsoft.com/cbl-mariner/base/core:2.0.20240628`) doesn't seem to have `systemctl` command. 
```
root [ / ]# systemctl
bash: systemctl: command not found
```

This is the version I am using. Let me know if I am using the wrong one.
```
docker pull mcr.microsoft.com/cbl-mariner/base/core:2.0.20240628
```

**Describe the solution you'd like**
Have `systemctl` available for Azure Linux Mariner.

**Comment by elsaco** [comment]
@TheOnlyWei this is the `core` version! Try the `full` version if you want `systemd` or run `tdnf install systemd`

**Comment by TheOnlyWei** [comment]
@elsaco Do you have a link to the version? I don't find any "full" versions when I search "mariner" in Microsoft Artifact Registry:
https://mcr.microsoft.com/en-us/catalog?search=mariner+full&page=1

**Comment by trungams** [comment]
@TheOnlyWei this is a late reply, but systemd is not available, and generally not needed/recommended in containers. To use systemctl command in Azure Linux, you can follow this [quick start guide](https://github.com/microsoft/azurelinux/blob/3.0/toolkit/docs/quick_start/quickstart.md) to create a VM on Hyper-V. Then you can use systemctl to manage services.

**Comment by jperrin** [comment]
some light github necromancy and clean-up. 

@trungams is correct. Using systemd in a container is not recommended except in very specific edge cases.
