### ISSUE TITLE
What's the ETA of WSL distribution be available in the Microsoft store?

### ISSUE THREAD

**Issue by yanchenzhang0304** [microsoft/azurelinux#9980]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by anupamsr** [comment]
Just FYI, one can install AzureLinux on WSL using `docker pull` and using that image.

**Comment by nicthegarden** [comment]
Could be interesting to have this available as in WSL.

**Comment by jperrin** [comment]
Some issue cleanup and necromancy. 

We cannot comment on timelines for things like this. Sorry.
